name: vmagent chocolatey packaging and publishing

on:
  push:
    branches:
    - main

jobs:
  choco-publishing:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Choco help
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: -h
      - name: Choco packaging
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack Choco\vmagent\vmagent.nuspec
      - name: Choco push
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push --source https://push.chocolatey.org/ -k ${{ secrets.CHOCO_API_KEY }}
