name: vmbackup-build

on:
  workflow_dispatch: # Allow to manually run the workflow.
  push:
    branches:
    - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set version
        run: |
          VER=v$(cat VERSION)
          echo "VM_VERSION=$VER" >> $GITHUB_ENV
      - name: Log in Github packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            symflower/vmbackup
            ghcr.io/symflower/vmbackup
          tags: |
            type=raw,value=${{ env.VM_VERSION }}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./vmbackup
          platforms: linux/386, linux/amd64, linux/arm, linux/arm64
          build-args: VM_VERSION=${{ env.VM_VERSION }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
